export const SET_DATA = "SET_DATA";
export const SET_CREDENTIALS = "SET_CREDENTIALS";
export const SET_IS_STATE_INITIALIZED = "SET_IS_STATE_INITIALIZED";
export const SET_IS_TEMPORARY_DRAWER_OPEN = "SET_IS_TEMPORARY_DRAWER_OPEN";
export const SET_IS_DRAWER_OPEN = "SET_IS_DRAWER_OPEN";
export const SET_ARE_DATASETS_SHOWING = "SET_ARE_DATASETS_SHOWING";
export const SET_INITIAL_OPEN_DRAWER_TAB_INDEX =
  "SET_INITIAL_OPEN_DRAWER_TAB_INDEX";
export const SET_DATE_PARAMETERS = "SET_DATE_PARAMETERS";
export const SET_IS_DATA_DOWNSAMPLED = "SET_IS_DATA_DOWNSAMPLED";
export const SET_IS_DATA_IN_PERCENT = "SET_IS_DATA_IN_PERCENT";
export const SET_IS_TABLE_HIDDEN = "SET_IS_TABLE_HIDDEN";
export const SET_FUND_NAMES_CURRENTLY_BEING_LOADED =
  "SET_FUND_NAMES_CURRENTLY_BEING_LOADED";
export const SET_SELECTED_TIMESPAN = "SET_SELECTED_TIMESPAN";
export const SET_FUND_DATA = "SET_FUND_DATA";
export const SET_IS_CHART_SHOWING = "SET_IS_CHART_SHOWING";
export const SET_FUND_NAME_LOADING = "SET_FUND_NAME_LOADING";
export const SET_FUND_NAME_HAS_LOADED = "SET_FUND_NAME_HAS_LOADED";
export const SET_SIGN_IN_USERNAME_INPUT_VALUE =
  "SET_SIGN_IN_USERNAME_INPUT_VALUE";
export const SET_SIGN_IN_PASSWORD_INPUT_VALUE =
  "SET_SIGN_IN_PASSWORD_INPUT_VALUE";
export const SET_SIGN_UP_USERNAME_INPUT_VALUE =
  "SET_SIGN_UP_USERNAME_INPUT_VALUE";
export const SET_SIGN_UP_PASSWORD_INPUT_VALUE =
  "SET_SIGN_UP_PASSWORD_INPUT_VALUE";
export const SET_IS_SIGN_IN_INVALID = "SET_IS_SIGN_IN_INVALID";
export const SET_IS_SIGN_UP_INVALID = "SET_IS_SIGN_UP_INVALID";
export const SET_IS_SIGN_UP_SHOWING = "SET_IS_SIGN_UP_SHOWING";

export const SET_ARE_PATTERNS_SHOWING = "SET_ARE_PATTERNS_SHOWING";

export const SET_SIGN_IN_USERNAME_ERROR_MESSAGE =
  "SET_SIGN_IN_USERNAME_ERROR_MESSAGE";
export const SET_SIGN_UP_USERNAME_ERROR_MESSAGE =
  "SET_SIGN_UP_USERNAME_ERROR_MESSAGE";

export const SET_SIGN_IN_PASSWORD_ERROR_MESSAGE =
  "SET_SIGN_IN_PASSWORD_ERROR_MESSAGE";
export const SET_SIGN_UP_PASSWORD_ERROR_MESSAGE =
  "SET_SIGN_UP_PASSWORD_ERROR_MESSAGE";
export const SET_IS_USER_REMEMBERED = "SET_IS_USER_REMEMBERED";

export const SET_IS_CHART_SHOWING_FOR_SMALL_SCREENS =
  "SET_IS_CHART_SHOWING_FOR_SMALL_SCREENS";

export const SET_ALERT_SETTINGS = "SET_ALERT_SETTINGS";

export const RESET_SIGN_IN_STATE = "RESET_SIGN_IN_STATE";
export const RESET_SIGN_UP_STATE = "RESET_SIGN_UP_STATE";
