export const SET_DATA = "SET_DATA";
export const SET_CREDENTIALS = "SET_CREDENTIALS";
export const SET_IS_STATE_INITIALIZED = "SET_IS_STATE_INITIALIZED";
export const SET_IS_TEMPORARY_DRAWER_OPEN = "SET_IS_TEMPORARY_DRAWER_OPEN";
export const SET_IS_DRAWER_OPEN = "SET_IS_DRAWER_OPEN";
export const SET_ARE_DATASETS_SHOWING = "SET_ARE_DATASETS_SHOWING";
export const SET_IS_SNACKBAR_HIDDEN = "SET_IS_SNACKBAR_HIDDEN";
export const SET_SNACKBAR_TEXT = "SET_SNACKBAR_TEXT";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const SET_SNACKBAR_SEVERITY = "SET_SNACKBAR_SEVERITY";
export const SET_INITIAL_OPEN_DRAWER_TAB_INDEX =
  "SET_INITIAL_OPEN_DRAWER_TAB_INDEX";
export const SET_DATE_PARAMETERS = "SET_DATE_PARAMETERS";
export const SET_IS_DATA_DOWNSAMPLED = "SET_IS_DATA_DOWNSAMPLED";
export const SET_IS_DATA_IN_PERCENT = "SET_IS_DATA_IN_PERCENT";
export const SET_IS_TABLE_HIDDEN = "SET_IS_TABLE_HIDDEN";
export const SET_FUND_NAMES_CURRENTLY_BEING_LOADED =
  "SET_FUND_NAMES_CURRENTLY_BEING_LOADED";
export const SET_SELECTED_TIMESPAN = "SET_SELECTED_TIMESPAN";
export const SET_FUND_DATA = "SET_FUND_DATA";
