export const SET_DATE_PARAMETERS = "SET_DATE_PARAMETERS";
export const SET_IS_DATA_DOWNSAMPLED = "SET_IS_DATA_DOWNSAMPLED";
export const SET_IS_DATA_IN_PERCENT = "SET_IS_DATA_IN_PERCENT";
export const SET_SELECTED_TIMESPAN = "SET_SELECTED_TIMESPAN";
export const SET_IS_CHART_SHOWING = "SET_IS_CHART_SHOWING";
export const SET_ARE_PATTERNS_SHOWING = "SET_ARE_PATTERNS_SHOWING";
export const SET_IS_CHART_SHOWING_FOR_SMALL_SCREENS =
  "SET_IS_CHART_SHOWING_FOR_SMALL_SCREENS";
