export const recommendedFunds = [
  ["Fidelity China Focus A-Acc-USD", "Buy"],
  ["GS India Equity Base Acc USD", "Buy"],
  ["Investec GSF Asian Equity A Acc USD", "Buy"],
  ["JOHCM European Select Val X EUR Inc", "Hold"],
  ["SEB Obligationsfond SEK", "Sell"],
];

export const data = {
  "Fidelity China Focus A-Acc-USD": {
    chartData: {
      _id: "Fidelity China Focus A-Acc-USD",
      indexFund: "MSCI China NR USD",
      morningstarRating: "4",
      ISIN: "LU1224709979",
      xData: [],
      yData: [],
    },
    tableData: {
      recommendation: "Buy",
      fundName: "Fidelity China Focus A-Acc-USD",
      ISIN: "LU1224709979",
      oneDC: "-1.76 %",
      oneYC: "-3.12 %",
      threeYC: "74.38 %",
      fiveYC: "23.59 %",
      morningstarRating: "4",
      mostRecentDate: "2019-05-13",
    },
  },
  "GS India Equity Base Acc USD": {
    chartData: {
      _id: "GS India Equity Base Acc USD",
      indexFund: "MSCI India NR USD",
      morningstarRating: "4",
      ISIN: "LU0333810181",
      xData: [],
      yData: [],
    },
    tableData: {
      recommendation: "Buy",
      fundName: "GS India Equity Base Acc USD",
      ISIN: "LU0333810181",
      oneDC: "-2.55 %",
      oneYC: "-1.46 %",
      threeYC: "41.38 %",
      fiveYC: "122.96 %",
      morningstarRating: "4",
      mostRecentDate: "2019-05-13",
    },
  },
  "Investec GSF Asian Equity A Acc USD": {
    chartData: {
      _id: "Investec GSF Asian Equity A Acc USD",
      indexFund: "MSCI AC Asia Ex Japan NR USD",
      morningstarRating: "4",
      ISIN: "LU0345775950",
      xData: [],
      yData: [],
    },
    tableData: {
      recommendation: "Buy",
      fundName: "Investec GSF Asian Equity A Acc USD",
      ISIN: "LU0345775950",
      oneDC: "-1.98 %",
      oneYC: "-4.18 %",
      threeYC: "70.94 %",
      fiveYC: "86.97 %",
      morningstarRating: "4",
      mostRecentDate: "2019-05-13",
    },
  },
  "JOHCM European Select Val X EUR Inc": {
    chartData: {
      _id: "JOHCM European Select Val X EUR Inc",
      indexFund: "MSCI Europe NR EUR",
      morningstarRating: "3",
      ISIN: "IE00B4K14L92",
      xData: [],
      yData: [],
    },
    tableData: {
      recommendation: "Hold",
      fundName: "JOHCM European Select Val X EUR Inc",
      ISIN: "IE00B4K14L92",
      oneDC: "-1.05 %",
      oneYC: "2.74 %",
      threeYC: "30.87 %",
      fiveYC: "52.81 %",
      morningstarRating: "3",
      mostRecentDate: "2019-05-13",
    },
  },
  "SEB Obligationsfond SEK": {
    chartData: {
      _id: "SEB Obligationsfond SEK",
      indexFund: "FTSE Swedish GBI SEK",
      morningstarRating: "2",
      ISIN: "SE0000984072",
      xData: [],
      yData: [],
    },
    tableData: {
      recommendation: "Sell",
      fundName: "SEB Obligationsfond SEK",
      ISIN: "SE0000984072",
      oneDC: "0.01 %",
      oneYC: "1.46 %",
      threeYC: "2.71 %",
      fiveYC: "8.64 %",
      morningstarRating: "2",
      mostRecentDate: "2019-05-13",
    },
  },
};
