export const SET_INITIAL_PORTFOLIO_STATE = "SET_INITIAL_PORTFOLIO_STATE";
export const SET_PORTFOLIO = "SET_PORTFOLIO";
export const BUY_FUND = "BUY_FUND";
export const SET_BALANCE = "SET_BALANCE";
export const SELL_FUND = "SELL_FUND";
export const SET_EXCHANGE_RATES = "SET_EXCHANGE_RATES";
export const SET_PORTFOLIO_FUND_NAME = "SET_PORTFOLIO_FUND_NAME";
export const SET_PORTFOLIO_DATE_PARAMETERS = "SET_PORTFOLIO_DATE_PARAMETERS";
