export const SET_CREDENTIALS = "SET_CREDENTIALS";

export const SET_SIGN_IN_USERNAME_INPUT_VALUE =
  "SET_SIGN_IN_USERNAME_INPUT_VALUE";
export const SET_SIGN_IN_PASSWORD_INPUT_VALUE =
  "SET_SIGN_IN_PASSWORD_INPUT_VALUE";
export const SET_SIGN_UP_USERNAME_INPUT_VALUE =
  "SET_SIGN_UP_USERNAME_INPUT_VALUE";
export const SET_SIGN_UP_PASSWORD_INPUT_VALUE =
  "SET_SIGN_UP_PASSWORD_INPUT_VALUE";
export const SET_IS_SIGN_IN_INVALID = "SET_IS_SIGN_IN_INVALID";
export const SET_IS_SIGN_UP_INVALID = "SET_IS_SIGN_UP_INVALID";
export const SET_IS_SIGN_UP_SHOWING = "SET_IS_SIGN_UP_SHOWING";

export const SET_SIGN_IN_USERNAME_ERROR_MESSAGE =
  "SET_SIGN_IN_USERNAME_ERROR_MESSAGE";
export const SET_SIGN_UP_USERNAME_ERROR_MESSAGE =
  "SET_SIGN_UP_USERNAME_ERROR_MESSAGE";

export const SET_SIGN_IN_PASSWORD_ERROR_MESSAGE =
  "SET_SIGN_IN_PASSWORD_ERROR_MESSAGE";
export const SET_SIGN_UP_PASSWORD_ERROR_MESSAGE =
  "SET_SIGN_UP_PASSWORD_ERROR_MESSAGE";
export const SET_IS_USER_REMEMBERED = "SET_IS_USER_REMEMBERED";

export const RESET_SIGN_IN_STATE = "RESET_SIGN_IN_STATE";
export const RESET_SIGN_UP_STATE = "RESET_SIGN_UP_STATE";
