export const SET_INITIAL_RECOMMENDED_FUNDS_STATE =
  "SET_INITIAL_RECOMMENDED_FUNDS_STATE";
export const SET_RECOMMENDED_DATE_PARAMETERS =
  "SET_RECOMMENDED_DATE_PARAMETERS";
export const SET_RECOMMENDED_FUND_NAME = "SET_RECOMMENDED_FUND_NAME";
export const SET_IS_INTRO_SHOWING = "SET_IS_INTRO_SHOWING";
export const SET_TAB_VALUE = "SET_TAB_VALUE";
